// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Wfmgr.Infrastructure.Persistence;

#nullable disable

namespace Wfmgr.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WfmgrDbContext))]
    partial class WfmgrDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Wfmgr.Infrastructure.Persistence.Entities.AuditLogEntity", b =>
                {
                    b.Property<Guid>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ActorId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FromStatus")
                        .HasColumnType("integer");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ToStatus")
                        .HasColumnType("integer");

                    b.HasKey("AuditId");

                    b.HasIndex("CaseId", "CreatedAt");

                    b.ToTable("AuditLog", (string)null);
                });

            modelBuilder.Entity("Wfmgr.Infrastructure.Persistence.Entities.CaseEntity", b =>
                {
                    b.Property<Guid>("CaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessionNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CtStudyInstanceUid")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CtWadoRsUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("CurrentStatus")
                        .HasColumnType("integer");

                    b.Property<string>("DepartmentId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("HospitalId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("PatientId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PvMedJobId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RtStructSeriesInstanceUid")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SiteId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("StatusVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CaseId");

                    b.HasIndex("CurrentStatus");

                    b.HasIndex("HospitalId", "SiteId", "DepartmentId", "AccessionNumber")
                        .IsUnique();

                    b.ToTable("Case", (string)null);
                });

            modelBuilder.Entity("Wfmgr.Infrastructure.Persistence.Entities.ExternalEventEntity", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CaseCorrelationKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Error")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProcessStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("EventId");

                    b.HasIndex("CaseId");

                    b.HasIndex("Source", "Type", "ExternalId")
                        .IsUnique();

                    b.ToTable("ExternalEvent", (string)null);
                });

            modelBuilder.Entity("Wfmgr.Infrastructure.Persistence.Entities.OutboxMessageEntity", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastTriedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TargetSystem")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("MessageId");

                    b.HasIndex("CaseId");

                    b.HasIndex("Status", "NextRetryAt");

                    b.ToTable("OutboxMessage", (string)null);
                });

            modelBuilder.Entity("Wfmgr.Infrastructure.Persistence.Entities.WorkItemEntity", b =>
                {
                    b.Property<Guid>("WorkItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssignedRole")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("AssignedUserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DueAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalCorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("text");

                    b.Property<int?>("SlaMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("WorkItemId");

                    b.HasIndex("CaseId");

                    b.HasIndex("Status");

                    b.HasIndex("AssignedRole", "Status");

                    b.ToTable("WorkItem", (string)null);
                });

            modelBuilder.Entity("Wfmgr.Infrastructure.Persistence.Entities.WorkflowProfileEntity", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DepartmentId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("HospitalId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SiteId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("ProfileId");

                    b.HasIndex("HospitalId", "SiteId", "DepartmentId", "Version")
                        .IsUnique();

                    b.ToTable("WorkflowProfile", (string)null);
                });

            modelBuilder.Entity("Wfmgr.Infrastructure.Persistence.Entities.WorkflowRuleEntity", b =>
                {
                    b.Property<Guid>("RuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConditionJson")
                        .HasColumnType("text");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("SlotCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("RuleId");

                    b.HasIndex("ProfileId", "SlotCode", "IsEnabled");

                    b.HasIndex("ProfileId", "SlotCode", "Priority");

                    b.ToTable("WorkflowRule", (string)null);
                });

            modelBuilder.Entity("Wfmgr.Infrastructure.Persistence.Entities.AuditLogEntity", b =>
                {
                    b.HasOne("Wfmgr.Infrastructure.Persistence.Entities.CaseEntity", "Case")
                        .WithMany("AuditLogs")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("Wfmgr.Infrastructure.Persistence.Entities.ExternalEventEntity", b =>
                {
                    b.HasOne("Wfmgr.Infrastructure.Persistence.Entities.CaseEntity", "Case")
                        .WithMany("ExternalEvents")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Case");
                });

            modelBuilder.Entity("Wfmgr.Infrastructure.Persistence.Entities.OutboxMessageEntity", b =>
                {
                    b.HasOne("Wfmgr.Infrastructure.Persistence.Entities.CaseEntity", "Case")
                        .WithMany("OutboxMessages")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Case");
                });

            modelBuilder.Entity("Wfmgr.Infrastructure.Persistence.Entities.WorkItemEntity", b =>
                {
                    b.HasOne("Wfmgr.Infrastructure.Persistence.Entities.CaseEntity", "Case")
                        .WithMany("WorkItems")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("Wfmgr.Infrastructure.Persistence.Entities.WorkflowRuleEntity", b =>
                {
                    b.HasOne("Wfmgr.Infrastructure.Persistence.Entities.WorkflowProfileEntity", "Profile")
                        .WithMany("Rules")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Wfmgr.Infrastructure.Persistence.Entities.CaseEntity", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("ExternalEvents");

                    b.Navigation("OutboxMessages");

                    b.Navigation("WorkItems");
                });

            modelBuilder.Entity("Wfmgr.Infrastructure.Persistence.Entities.WorkflowProfileEntity", b =>
                {
                    b.Navigation("Rules");
                });
#pragma warning restore 612, 618
        }
    }
}
